### ISSUE TITLE
Cant authenticate with HDS client to my localhost server.

### ISSUE THREAD

**Issue by PabloMonfort** [hdneo/mxo-hd#3]
i try to make a localhost server and it runs fine the server but i cant authenticate , i used loluser lolpass but it just disconnect with authenticating failure to client right when send the public async ProcessGetPublicKey_Request response... i get stuck here and i dont know how to continue to try login, can anyone give me a hand ? what im missing? can you doc more please how we can host a localhost server of this so we can help you out if want im C# junnior programmer , and independent game developer. have fun thanks for read.

**Comment by PabloMonfort** [comment]
![image](https://user-images.githubusercontent.com/30636592/137649875-247da73e-2e1e-4a24-bd95-044b02473a22.png)
just want to attach the picture . thanks for your time.

**Comment by hdneo** [comment]
first: we are both senior c# devs with at least over 10 years experience in it.
Also C# is not the tricky part - gettin in MxO stuff is the tricky part. 

However - as i told you in disord this will be happen when the new release comes (so no for now). 
But i let it stay open for now so that we dont forget about it.

**Comment by hdneo** [comment]
"we can help you out if want im C# junnior programmer" - i just said this as you told that you are a junior dev.

However: i gave you the info you need to setup client. 
I ALSO told you that this code is obsolete and for this code there is no help necessary.

we dont need your help at the current stage for developing. That would make more work as it would help and thats time that cost our lifetime.

If you are even unable to connect to the hds server - how you wanna help ? 
I guess there is still some wrong RSA stuff issue - i dont know...

As i ALSO told you: i wouldnt care about it for now - when the new server will be more in state where devs CAN do stuff : then we can talk about.

Because you are so piggy i now close your request- kkthxbyebye.
